---
platform: linux

image-resource: docker:///brianbyers/concourse-gradle
image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"


inputs:
  - name: git-repo

run:
  path: git-repo/ci/tasks/unit.sh
